"""
End-to-end integration test for {system_name}.

This test validates the complete workflow from user request to agent delegation
and result aggregation without requiring cloud credentials (uses mock agents).
Generated by AgentBuilder on {timestamp}.
"""

import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from coordinator.main import {coordinator_class_name}, DelegationDecision, AgentResult


{mock_agent_classes}


def test_single_agent_delegation():
    """Test delegation to a single agent."""
    print("\\n=== Test 1: Single Agent Delegation ===")

    coordinator = {coordinator_class_name}()
    mock_agent = {first_mock_agent}()
    coordinator.register_specialized_agent('{first_agent_name}', mock_agent)

    request = "{first_test_request}"
    response = coordinator.process_request(request)

    # Validate response structure
    assert 'request' in response
    assert 'delegations' in response
    assert 'results' in response
    assert response['request'] == request

    # Validate results
    aggregated = response['results']
    assert aggregated['success'] is True
    assert 'insights' in aggregated

    print("[PASS] Single agent delegation test passed")
    return True


def test_multi_agent_delegation():
    """Test delegation to multiple agents."""
    print("\\n=== Test 2: Multi-Agent Delegation ===")

    coordinator = {coordinator_class_name}()

    # Register ALL specialized agents
{agent_registrations}

    request = "{multi_agent_test_request}"
    response = coordinator.process_request(request)

    # Validate multiple delegations
    assert len(response['delegations']) >= 2

    # Validate all agents succeeded
    aggregated = response['results']
    assert aggregated['success'] is True

    print("[PASS] Multi-agent delegation test passed")
    return True


def test_result_aggregation():
    """Test aggregation of results from multiple agents."""
    print("\\n=== Test 3: Result Aggregation ===")

    coordinator = {coordinator_class_name}()

    # Create mock results
    results = [
{mock_results}
    ]

    # Aggregate results
    aggregated = coordinator.aggregate_results(results)

    # Validate aggregation
    assert aggregated['success'] is True
    assert len(aggregated['insights']) == {num_agents}

    print("[PASS] Result aggregation test passed")
    return True


def test_delegation_statistics():
    """Test delegation statistics tracking."""
    print("\\n=== Test 4: Delegation Statistics ===")

    coordinator = {coordinator_class_name}()

    # Register agents
{stats_agent_registrations}

    # Process multiple requests
{stats_test_requests}

    # Get statistics
    stats = coordinator.get_delegation_stats()

    # Validate statistics
    assert stats['total_delegations'] >= 3
    assert 'delegations_by_agent' in stats
    assert 'success_rate' in stats

    print("[PASS] Delegation statistics test passed")
    return True


def test_error_handling():
    """Test error handling when agent is not registered."""
    print("\\n=== Test 5: Error Handling ===")

    coordinator = {coordinator_class_name}()

    # Create delegation to non-existent agent
    decision = DelegationDecision(
        target_agent='nonexistent_agent',
        task_description='Test task',
        parameters={{}}
    )

    # Execute delegation
    result = coordinator.execute_delegation(decision)

    # Validate error handling
    assert result.success is False
    assert result.error is not None
    assert 'not registered' in result.error

    print("[PASS] Error handling test passed")
    return True


def test_complete_workflow():
    """Test complete workflow with all agents."""
    print("\\n=== Test 6: Complete Workflow (All Agents) ===")

    coordinator = {coordinator_class_name}()

    # Register ALL agents
{complete_workflow_registrations}

    # Test workflow requests
    workflow_requests = [
{workflow_requests}
    ]

    results = []
    for request in workflow_requests:
        response = coordinator.process_request(request)
        results.append(response)
        assert response['results']['success'] is True, f"Failed request: {{request}}"

    print(f"[PASS] Complete workflow test passed - {{len(results)}} agents executed")
    return True


def run_integration_tests():
    """Run all integration tests."""
    print("\\n" + "="*60)
    print("{system_name} - INTEGRATION TESTS")
    print("="*60)

    tests = [
        test_single_agent_delegation,
        test_multi_agent_delegation,
        test_result_aggregation,
        test_delegation_statistics,
        test_error_handling,
        test_complete_workflow,
    ]

    passed = 0
    failed = 0

    for test in tests:
        try:
            test()
            passed += 1
        except AssertionError as e:
            failed += 1
            print(f"[FAIL] Test failed: {{test.__name__}}")
            print(f"   Error: {{str(e)}}")
        except Exception as e:
            failed += 1
            print(f"[ERROR] Test error: {{test.__name__}}")
            print(f"   Error: {{str(e)}}")

    # Print summary
    print("\\n" + "="*60)
    print("INTEGRATION TEST SUMMARY")
    print("="*60)
    print(f"Total tests: {{passed + failed}}")
    print(f"Passed: {{passed}}")
    print(f"Failed: {{failed}}")
    print(f"Success rate: {{(passed / (passed + failed) * 100):.1f}}%")
    print("="*60 + "\\n")

    return failed == 0


if __name__ == "__main__":
    success = run_integration_tests()
    sys.exit(0 if success else 1)
